export const blogs = [

[
    {
        heading:'What is Data Science and how does it works',
        img: '/assets/images/blogs/ds.jpg',
        subHeading: '',
        content: [
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
            'Lorem ipsum dolorLorem ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae, facere. Quas, architecto inventore nam, provident quia commodi odit doloribus ducimus et temporibus facere! Suscipit, asperiores nobis aperiam quod consequatur eos commodi explicabo error iusto sapiente modi dolor repellat consectetur aliquam obcaecati aspernatur. Laborum unde nulla consequatur, dignissimos quod quas, maxime eligendi ipsam omnis voluptate provident tempora. Ad quos ea perspiciatis, voluptate quaerat quia et debitis magni error iusto animi, optio similique earum eveniet, beatae sed? Autem voluptas, ullam numquam vero error optio. Ad molestiae hic sed provident eos quia quaerat deleniti, nihil obcaecati distinctio ducimus ipsa labore aspernatur quidem in exercitationem nobis corrupti iste eum, porro sequi voluptates. Commodi sed cum, maxime assumenda, quos eligendi dolorum, incidunt magnam velit amet quod vero? Eaque autem debitis vero eius aut sequi cumque perspiciatis omnis ipsa eos sapiente repellendus temporibus, veritatis quis hic repellat est accusantium asperiores et iste dolor. Veritatis, illum molestiae! Dicta accusantium repellendus natus, illum dolor, quae laboriosam, hic saepe assumenda incidunt cupiditate maiores. Laborum reiciendis mollitia repellat debitis exercitationem, fugit perspiciatis. Dolor itaque necessitatibus a doloribus voluptatum dolorem ab vitae eveniet quaerat molestias temporibus corrupti cupiditate veritatis ullam explicabo excepturi laboriosam delectus, illum vero, iste veniam fugit quam quidem. sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
            'Lorem ipsum dolorLorem ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae, facere. Quas, architecto inventore nam, provident quia commodi odit doloribus ducimus et temporibus facere! Suscipit, asperiores nobis aperiam quod consequatur eos commodi explicabo error iusto sapiente modi dolor repellat consectetur aliquam obcaecati aspernatur. Laborum unde nulla consequatur, dignissimos quod quas, maxime eligendi ipsam omnis voluptate provident tempora. Ad quos ea perspiciatis, voluptate quaerat quia et debitis magni error iusto animi, optio similique earum eveniet, beatae sed? Autem voluptas, ullam numquam vero error optio. Ad molestiae hic sed provident eos quia quaerat deleniti, nihil obcaecati distinctio ducimus ipsa labore aspernatur quidem in exercitationem nobis corrupti iste eum, porro sequi voluptates. Commodi sed cum, maxime assumenda, quos eligendi dolorum, incidunt magnam velit amet quod vero? Eaque autem debitis vero eius aut sequi cumque perspiciatis omnis ipsa eos sapiente repellendus temporibus, veritatis quis hic repellat est accusantium asperiores et iste dolor. Veritatis, illum molestiae! Dicta accusantium repellendus natus, illum dolor, quae laboriosam, hic saepe assumenda incidunt cupiditate maiores. Laborum reiciendis mollitia repellat debitis exercitationem, fugit perspiciatis. Dolor itaque necessitatibus a doloribus voluptatum dolorem ab vitae eveniet quaerat molestias temporibus corrupti cupiditate veritatis ullam explicabo excepturi laboriosam delectus, illum vero, iste veniam fugit quam quidem. sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
        ]
    },
    {
        heading:'What is Machine Learing and how does it works',
        img: '/assets/images/blogs/code.svg',
        subHeading: '',
        content: [
            'Lorem ipsum dolorLorem ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae, facere. Quas, architecto inventore nam, provident quia commodi odit doloribus ducimus et temporibus facere! Suscipit, asperiores nobis aperiam quod consequatur eos commodi explicabo error iusto sapiente modi dolor repellat consectetur aliquam obcaecati aspernatur. Laborum unde nulla consequatur, dignissimos quod quas, maxime eligendi ipsam omnis voluptate provident tempora. Ad quos ea perspiciatis, voluptate quaerat quia et debitis magni error iusto animi, optio similique earum eveniet, beatae sed? Autem voluptas, ullam numquam vero error optio. Ad molestiae hic sed provident eos quia quaerat deleniti, nihil obcaecati distinctio ducimus ipsa labore aspernatur quidem in exercitationem nobis corrupti iste eum, porro sequi voluptates. Commodi sed cum, maxime assumenda, quos eligendi dolorum, incidunt magnam velit amet quod vero? Eaque autem debitis vero eius aut sequi cumque perspiciatis omnis ipsa eos sapiente repellendus temporibus, veritatis quis hic repellat est accusantium asperiores et iste dolor. Veritatis, illum molestiae! Dicta accusantium repellendus natus, illum dolor, quae laboriosam, hic saepe assumenda incidunt cupiditate maiores. Laborum reiciendis mollitia repellat debitis exercitationem, fugit perspiciatis. Dolor itaque necessitatibus a doloribus voluptatum dolorem ab vitae eveniet quaerat molestias temporibus corrupti cupiditate veritatis ullam explicabo excepturi laboriosam delectus, illum vero, iste veniam fugit quam quidem. sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
            'Lorem ipsum dolorLorem ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae, facere. Quas, architecto inventore nam, provident quia commodi odit doloribus ducimus et temporibus facere! Suscipit, asperiores nobis aperiam quod consequatur eos commodi explicabo error iusto sapiente modi dolor repellat consectetur aliquam obcaecati aspernatur. Laborum unde nulla consequatur, dignissimos quod quas, maxime eligendi ipsam omnis voluptate provident tempora. Ad quos ea perspiciatis, voluptate quaerat quia et debitis magni error iusto animi, optio similique earum eveniet, beatae sed? Autem voluptas, ullam numquam vero error optio. Ad molestiae hic sed provident eos quia quaerat deleniti, nihil obcaecati distinctio ducimus ipsa labore aspernatur quidem in exercitationem nobis corrupti iste eum, porro sequi voluptates. Commodi sed cum, maxime assumenda, quos eligendi dolorum, incidunt magnam velit amet quod vero? Eaque autem debitis vero eius aut sequi cumque perspiciatis omnis ipsa eos sapiente repellendus temporibus, veritatis quis hic repellat est accusantium asperiores et iste dolor. Veritatis, illum molestiae! Dicta accusantium repellendus natus, illum dolor, quae laboriosam, hic saepe assumenda incidunt cupiditate maiores. Laborum reiciendis mollitia repellat debitis exercitationem, fugit perspiciatis. Dolor itaque necessitatibus a doloribus voluptatum dolorem ab vitae eveniet quaerat molestias temporibus corrupti cupiditate veritatis ullam explicabo excepturi laboriosam delectus, illum vero, iste veniam fugit quam quidem. sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
        ]
    },
    {
        heading:'What is RPA and how does it works',
        img: '/assets/images/blogs/rpa.svg',
        subHeading: '',
        content: [
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
            'Lorem ipsum dolorLorem ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae, facere. Quas, architecto inventore nam, provident quia commodi odit doloribus ducimus et temporibus facere! Suscipit, asperiores nobis aperiam quod consequatur eos commodi explicabo error iusto sapiente modi dolor repellat consectetur aliquam obcaecati aspernatur. Laborum unde nulla consequatur, dignissimos quod quas, maxime eligendi ipsam omnis voluptate provident tempora. Ad quos ea perspiciatis, voluptate quaerat quia et debitis magni error iusto animi, optio similique earum eveniet, beatae sed? Autem voluptas, ullam numquam vero error optio. Ad molestiae hic sed provident eos quia quaerat deleniti, nihil obcaecati distinctio ducimus ipsa labore aspernatur quidem in exercitationem nobis corrupti iste eum, porro sequi voluptates. Commodi sed cum, maxime assumenda, quos eligendi dolorum, incidunt magnam velit amet quod vero? Eaque autem debitis vero eius aut sequi cumque perspiciatis omnis ipsa eos sapiente repellendus temporibus, veritatis quis hic repellat est accusantium asperiores et iste dolor. Veritatis, illum molestiae! Dicta accusantium repellendus natus, illum dolor, quae laboriosam, hic saepe assumenda incidunt cupiditate maiores. Laborum reiciendis mollitia repellat debitis exercitationem, fugit perspiciatis. Dolor itaque necessitatibus a doloribus voluptatum dolorem ab vitae eveniet quaerat molestias temporibus corrupti cupiditate veritatis ullam explicabo excepturi laboriosam delectus, illum vero, iste veniam fugit quam quidem. sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
            'Lorem ipsum dolorLorem ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae, facere. Quas, architecto inventore nam, provident quia commodi odit doloribus ducimus et temporibus facere! Suscipit, asperiores nobis aperiam quod consequatur eos commodi explicabo error iusto sapiente modi dolor repellat consectetur aliquam obcaecati aspernatur. Laborum unde nulla consequatur, dignissimos quod quas, maxime eligendi ipsam omnis voluptate provident tempora. Ad quos ea perspiciatis, voluptate quaerat quia et debitis magni error iusto animi, optio similique earum eveniet, beatae sed? Autem voluptas, ullam numquam vero error optio. Ad molestiae hic sed provident eos quia quaerat deleniti, nihil obcaecati distinctio ducimus ipsa labore aspernatur quidem in exercitationem nobis corrupti iste eum, porro sequi voluptates. Commodi sed cum, maxime assumenda, quos eligendi dolorum, incidunt magnam velit amet quod vero? Eaque autem debitis vero eius aut sequi cumque perspiciatis omnis ipsa eos sapiente repellendus temporibus, veritatis quis hic repellat est accusantium asperiores et iste dolor. Veritatis, illum molestiae! Dicta accusantium repellendus natus, illum dolor, quae laboriosam, hic saepe assumenda incidunt cupiditate maiores. Laborum reiciendis mollitia repellat debitis exercitationem, fugit perspiciatis. Dolor itaque necessitatibus a doloribus voluptatum dolorem ab vitae eveniet quaerat molestias temporibus corrupti cupiditate veritatis ullam explicabo excepturi laboriosam delectus, illum vero, iste veniam fugit quam quidem. sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
        ]
    },
],

[
    
        {
            heading:'What is Social Meadia Marketing',
            img: '/assets/images/blogs/dm.png',
            subHeading: '',
            content: [
                'Lorem ipsumLorem ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae, facere. Quas, architecto inventore nam, provident quia commodi odit doloribus ducimus et temporibus facere! Suscipit, asperiores nobis aperiam quod consequatur eos commodi explicabo error iusto sapiente modi dolor repellat consectetur aliquam obcaecati aspernatur. Laborum unde nulla consequatur, dignissimos quod quas, maxime eligendi ipsam omnis voluptate provident tempora. Ad quos ea perspiciatis, voluptate quaerat quia et debitis magni error iusto animi, optio similique earum eveniet, beatae sed? Autem voluptas, ullam numquam vero error optio. Ad molestiae hic sed provident eos quia quaerat deleniti, nihil obcaecati distinctio ducimus ipsa labore aspernatur quidem in exercitationem nobis corrupti iste eum, porro sequi voluptates. Commodi sed cum, maxime assumenda, quos eligendi dolorum, incidunt magnam velit amet quod vero? Eaque autem debitis vero eius aut sequi cumque perspiciatis omnis ipsa eos sapiente repellendus temporibus, veritatis quis hic repellat est accusantium asperiores et iste dolor. Veritatis, illum molestiae! Dicta accusantium repellendus natus, illum dolor, quae laboriosam, hic saepe assumenda incidunt cupiditate maiores. Laborum reiciendis mollitia repellat debitis exercitationem, fugit perspiciatis. Dolor itaque necessitatibus a doloribus voluptatum dolorem ab vitae eveniet quaerat molestias temporibus corrupti cupiditate veritatis ullam explicabo excepturi laboriosam delectus, illum vero, iste veniam fugit quam quidem. dolor sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
                'Lorem ipsum dolor sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
                'Lorem ipsumLorem ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae, facere. Quas, architecto inventore nam, provident quia commodi odit doloribus ducimus et temporibus facere! Suscipit, asperiores nobis aperiam quod consequatur eos commodi explicabo error iusto sapiente modi dolor repellat consectetur aliquam obcaecati aspernatur. Laborum unde nulla consequatur, dignissimos quod quas, maxime eligendi ipsam omnis voluptate provident tempora. Ad quos ea perspiciatis, voluptate quaerat quia et debitis magni error iusto animi, optio similique earum eveniet, beatae sed? Autem voluptas, ullam numquam vero error optio. Ad molestiae hic sed provident eos quia quaerat deleniti, nihil obcaecati distinctio ducimus ipsa labore aspernatur quidem in exercitationem nobis corrupti iste eum, porro sequi voluptates. Commodi sed cum, maxime assumenda, quos eligendi dolorum, incidunt magnam velit amet quod vero? Eaque autem debitis vero eius aut sequi cumque perspiciatis omnis ipsa eos sapiente repellendus temporibus, veritatis quis hic repellat est accusantium asperiores et iste dolor. Veritatis, illum molestiae! Dicta accusantium repellendus natus, illum dolor, quae laboriosam, hic saepe assumenda incidunt cupiditate maiores. Laborum reiciendis mollitia repellat debitis exercitationem, fugit perspiciatis. Dolor itaque necessitatibus a doloribus voluptatum dolorem ab vitae eveniet quaerat molestias temporibus corrupti cupiditate veritatis ullam explicabo excepturi laboriosam delectus, illum vero, iste veniam fugit quam quidem. dolor sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
                'Lorem ipsum dolor sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
            ]
        },
        {
            heading:'How can you grow your business with digital marketing',
            img: '/assets/images/blogs/creative.jpg',
            subHeading: '',
            content: [
                'Lorem ipsum dolor sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
                'Lorem ipsumLorem ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae, facere. Quas, architecto inventore nam, provident quia commodi odit doloribus ducimus et temporibus facere! Suscipit, asperiores nobis aperiam quod consequatur eos commodi explicabo error iusto sapiente modi dolor repellat consectetur aliquam obcaecati aspernatur. Laborum unde nulla consequatur, dignissimos quod quas, maxime eligendi ipsam omnis voluptate provident tempora. Ad quos ea perspiciatis, voluptate quaerat quia et debitis magni error iusto animi, optio similique earum eveniet, beatae sed? Autem voluptas, ullam numquam vero error optio. Ad molestiae hic sed provident eos quia quaerat deleniti, nihil obcaecati distinctio ducimus ipsa labore aspernatur quidem in exercitationem nobis corrupti iste eum, porro sequi voluptates. Commodi sed cum, maxime assumenda, quos eligendi dolorum, incidunt magnam velit amet quod vero? Eaque autem debitis vero eius aut sequi cumque perspiciatis omnis ipsa eos sapiente repellendus temporibus, veritatis quis hic repellat est accusantium asperiores et iste dolor. Veritatis, illum molestiae! Dicta accusantium repellendus natus, illum dolor, quae laboriosam, hic saepe assumenda incidunt cupiditate maiores. Laborum reiciendis mollitia repellat debitis exercitationem, fugit perspiciatis. Dolor itaque necessitatibus a doloribus voluptatum dolorem ab vitae eveniet quaerat molestias temporibus corrupti cupiditate veritatis ullam explicabo excepturi laboriosam delectus, illum vero, iste veniam fugit quam quidem. dolor sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
                'Lorem ipsum dolor sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
                'Lorem ipsum Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae, facere. Quas, architecto inventore nam, provident quia commodi odit doloribus ducimus et temporibus facere! Suscipit, asperiores nobis aperiam quod consequatur eos commodi explicabo error iusto sapiente modi dolor repellat consectetur aliquam obcaecati aspernatur. Laborum unde nulla consequatur, dignissimos quod quas, maxime eligendi ipsam omnis voluptate provident tempora. Ad quos ea perspiciatis, voluptate quaerat quia et debitis magni error iusto animi, optio similique earum eveniet, beatae sed? Autem voluptas, ullam numquam vero error optio. Ad molestiae hic sed provident eos quia quaerat deleniti, nihil obcaecati distinctio ducimus ipsa labore aspernatur quidem in exercitationem nobis corrupti iste eum, porro sequi voluptates. Commodi sed cum, maxime assumenda, quos eligendi dolorum, incidunt magnam velit amet quod vero? Eaque autem debitis vero eius aut sequi cumque perspiciatis omnis ipsa eos sapiente repellendus temporibus, veritatis quis hic repellat est accusantium asperiores et iste dolor. Veritatis, illum molestiae! Dicta accusantium repellendus natus, illum dolor, quae laboriosam, hic saepe assumenda incidunt cupiditate maiores. Laborum reiciendis mollitia repellat debitis exercitationem, fugit perspiciatis. Dolor itaque necessitatibus a doloribus voluptatum dolorem ab vitae eveniet quaerat molestias temporibus corrupti cupiditate veritatis ullam explicabo excepturi laboriosam delectus, illum vero, iste veniam fugit quam quidem.dolor sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
            ]
        },
        {
            heading:'What is SEO and how does it works',
            img: '/assets/images/blogs/seo.jpg',
            subHeading: '',
            content: [
                'Lorem ipsum Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae, facere. Quas, architecto inventore nam, provident quia commodi odit doloribus ducimus et temporibus facere! Suscipit, asperiores nobis aperiam quod consequatur eos commodi explicabo error iusto sapiente modi dolor repellat consectetur aliquam obcaecati aspernatur. Laborum unde nulla consequatur, dignissimos quod quas, maxime eligendi ipsam omnis voluptate provident tempora. Ad quos ea perspiciatis, voluptate quaerat quia et debitis magni error iusto animi, optio similique earum eveniet, beatae sed? Autem voluptas, ullam numquam vero error optio. Ad molestiae hic sed provident eos quia quaerat deleniti, nihil obcaecati distinctio ducimus ipsa labore aspernatur quidem in exercitationem nobis corrupti iste eum, porro sequi voluptates. Commodi sed cum, maxime assumenda, quos eligendi dolorum, incidunt magnam velit amet quod vero? Eaque autem debitis vero eius aut sequi cumque perspiciatis omnis ipsa eos sapiente repellendus temporibus, veritatis quis hic repellat est accusantium asperiores et iste dolor. Veritatis, illum molestiae! Dicta accusantium repellendus natus, illum dolor, quae laboriosam, hic saepe assumenda incidunt cupiditate maiores. Laborum reiciendis mollitia repellat debitis exercitationem, fugit perspiciatis. Dolor itaque necessitatibus a doloribus voluptatum dolorem ab vitae eveniet quaerat molestias temporibus corrupti cupiditate veritatis ullam explicabo excepturi laboriosam delectus, illum vero, iste veniam fugit quam quidem.dolor sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
                'Lorem ipsum dolor sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
                'Lorem ipsumLorem ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae, facere. Quas, architecto inventore nam, provident quia commodi odit doloribus ducimus et temporibus facere! Suscipit, asperiores nobis aperiam quod consequatur eos commodi explicabo error iusto sapiente modi dolor repellat consectetur aliquam obcaecati aspernatur. Laborum unde nulla consequatur, dignissimos quod quas, maxime eligendi ipsam omnis voluptate provident tempora. Ad quos ea perspiciatis, voluptate quaerat quia et debitis magni error iusto animi, optio similique earum eveniet, beatae sed? Autem voluptas, ullam numquam vero error optio. Ad molestiae hic sed provident eos quia quaerat deleniti, nihil obcaecati distinctio ducimus ipsa labore aspernatur quidem in exercitationem nobis corrupti iste eum, porro sequi voluptates. Commodi sed cum, maxime assumenda, quos eligendi dolorum, incidunt magnam velit amet quod vero? Eaque autem debitis vero eius aut sequi cumque perspiciatis omnis ipsa eos sapiente repellendus temporibus, veritatis quis hic repellat est accusantium asperiores et iste dolor. Veritatis, illum molestiae! Dicta accusantium repellendus natus, illum dolor, quae laboriosam, hic saepe assumenda incidunt cupiditate maiores. Laborum reiciendis mollitia repellat debitis exercitationem, fugit perspiciatis. Dolor itaque necessitatibus a doloribus voluptatum dolorem ab vitae eveniet quaerat molestias temporibus corrupti cupiditate veritatis ullam explicabo excepturi laboriosam delectus, illum vero, iste veniam fugit quam quidem. dolor sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
                'Lorem ipsum dolor sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
            ]
        },
    
],

[
    
        {
            heading:'Most demanding jobs in IT-Sector by 2022',
            img: '/assets/images/blogs/openSourse.svg',
            subHeading: '',
            content: [
                'Lorem ipsum dolor sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
                'Lorem ipsumLorem ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae, facere. Quas, architecto inventore nam, provident quia commodi odit doloribus ducimus et temporibus facere! Suscipit, asperiores nobis aperiam quod consequatur eos commodi explicabo error iusto sapiente modi dolor repellat consectetur aliquam obcaecati aspernatur. Laborum unde nulla consequatur, dignissimos quod quas, maxime eligendi ipsam omnis voluptate provident tempora. Ad quos ea perspiciatis, voluptate quaerat quia et debitis magni error iusto animi, optio similique earum eveniet, beatae sed? Autem voluptas, ullam numquam vero error optio. Ad molestiae hic sed provident eos quia quaerat deleniti, nihil obcaecati distinctio ducimus ipsa labore aspernatur quidem in exercitationem nobis corrupti iste eum, porro sequi voluptates. Commodi sed cum, maxime assumenda, quos eligendi dolorum, incidunt magnam velit amet quod vero? Eaque autem debitis vero eius aut sequi cumque perspiciatis omnis ipsa eos sapiente repellendus temporibus, veritatis quis hic repellat est accusantium asperiores et iste dolor. Veritatis, illum molestiae! Dicta accusantium repellendus natus, illum dolor, quae laboriosam, hic saepe assumenda incidunt cupiditate maiores. Laborum reiciendis mollitia repellat debitis exercitationem, fugit perspiciatis. Dolor itaque necessitatibus a doloribus voluptatum dolorem ab vitae eveniet quaerat molestias temporibus corrupti cupiditate veritatis ullam explicabo excepturi laboriosam delectus, illum vero, iste veniam fugit quam quidem. dolor sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
                'Lorem ipsum dolor sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
                'Lorem ipsumLorem ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae, facere. Quas, architecto inventore nam, provident quia commodi odit doloribus ducimus et temporibus facere! Suscipit, asperiores nobis aperiam quod consequatur eos commodi explicabo error iusto sapiente modi dolor repellat consectetur aliquam obcaecati aspernatur. Laborum unde nulla consequatur, dignissimos quod quas, maxime eligendi ipsam omnis voluptate provident tempora. Ad quos ea perspiciatis, voluptate quaerat quia et debitis magni error iusto animi, optio similique earum eveniet, beatae sed? Autem voluptas, ullam numquam vero error optio. Ad molestiae hic sed provident eos quia quaerat deleniti, nihil obcaecati distinctio ducimus ipsa labore aspernatur quidem in exercitationem nobis corrupti iste eum, porro sequi voluptates. Commodi sed cum, maxime assumenda, quos eligendi dolorum, incidunt magnam velit amet quod vero? Eaque autem debitis vero eius aut sequi cumque perspiciatis omnis ipsa eos sapiente repellendus temporibus, veritatis quis hic repellat est accusantium asperiores et iste dolor. Veritatis, illum molestiae! Dicta accusantium repellendus natus, illum dolor, quae laboriosam, hic saepe assumenda incidunt cupiditate maiores. Laborum reiciendis mollitia repellat debitis exercitationem, fugit perspiciatis. Dolor itaque necessitatibus a doloribus voluptatum dolorem ab vitae eveniet quaerat molestias temporibus corrupti cupiditate veritatis ullam explicabo excepturi laboriosam delectus, illum vero, iste veniam fugit quam quidem. dolor sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
            ]
        },
        {
            heading:'How to get a fresher job as a web developer',
            img: '/assets/images/blogs/code.svg',
            subHeading: '',
            content: [
                'Lorem ipsum Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae, facere. Quas, architecto inventore nam, provident quia commodi odit doloribus ducimus et temporibus facere! Suscipit, asperiores nobis aperiam quod consequatur eos commodi explicabo error iusto sapiente modi dolor repellat consectetur aliquam obcaecati aspernatur. Laborum unde nulla consequatur, dignissimos quod quas, maxime eligendi ipsam omnis voluptate provident tempora. Ad quos ea perspiciatis, voluptate quaerat quia et debitis magni error iusto animi, optio similique earum eveniet, beatae sed? Autem voluptas, ullam numquam vero error optio. Ad molestiae hic sed provident eos quia quaerat deleniti, nihil obcaecati distinctio ducimus ipsa labore aspernatur quidem in exercitationem nobis corrupti iste eum, porro sequi voluptates. Commodi sed cum, maxime assumenda, quos eligendi dolorum, incidunt magnam velit amet quod vero? Eaque autem debitis vero eius aut sequi cumque perspiciatis omnis ipsa eos sapiente repellendus temporibus, veritatis quis hic repellat est accusantium asperiores et iste dolor. Veritatis, illum molestiae! Dicta accusantium repellendus natus, illum dolor, quae laboriosam, hic saepe assumenda incidunt cupiditate maiores. Laborum reiciendis mollitia repellat debitis exercitationem, fugit perspiciatis. Dolor itaque necessitatibus a doloribus voluptatum dolorem ab vitae eveniet quaerat molestias temporibus corrupti cupiditate veritatis ullam explicabo excepturi laboriosam delectus, illum vero, iste veniam fugit quam quidem.dolor sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
                'Lorem ipsum dolor sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
                'Lorem ipsum Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae, facere. Quas, architecto inventore nam, provident quia commodi odit doloribus ducimus et temporibus facere! Suscipit, asperiores nobis aperiam quod consequatur eos commodi explicabo error iusto sapiente modi dolor repellat consectetur aliquam obcaecati aspernatur. Laborum unde nulla consequatur, dignissimos quod quas, maxime eligendi ipsam omnis voluptate provident tempora. Ad quos ea perspiciatis, voluptate quaerat quia et debitis magni error iusto animi, optio similique earum eveniet, beatae sed? Autem voluptas, ullam numquam vero error optio. Ad molestiae hic sed provident eos quia quaerat deleniti, nihil obcaecati distinctio ducimus ipsa labore aspernatur quidem in exercitationem nobis corrupti iste eum, porro sequi voluptates. Commodi sed cum, maxime assumenda, quos eligendi dolorum, incidunt magnam velit amet quod vero? Eaque autem debitis vero eius aut sequi cumque perspiciatis omnis ipsa eos sapiente repellendus temporibus, veritatis quis hic repellat est accusantium asperiores et iste dolor. Veritatis, illum molestiae! Dicta accusantium repellendus natus, illum dolor, quae laboriosam, hic saepe assumenda incidunt cupiditate maiores. Laborum reiciendis mollitia repellat debitis exercitationem, fugit perspiciatis. Dolor itaque necessitatibus a doloribus voluptatum dolorem ab vitae eveniet quaerat molestias temporibus corrupti cupiditate veritatis ullam explicabo excepturi laboriosam delectus, illum vero, iste veniam fugit quam quidem.dolor sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
                'Lorem ipsum dolor sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
            ]
        },
        {
            heading:'How to land your internship in Data Science ',
            img: '/assets/images/blogs/edu.svg',
            subHeading: '',
            content: [
                'Lorem ipsum dolor sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
                'Lorem ipsumLorem ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae, facere. Quas, architecto inventore nam, provident quia commodi odit doloribus ducimus et temporibus facere! Suscipit, asperiores nobis aperiam quod consequatur eos commodi explicabo error iusto sapiente modi dolor repellat consectetur aliquam obcaecati aspernatur. Laborum unde nulla consequatur, dignissimos quod quas, maxime eligendi ipsam omnis voluptate provident tempora. Ad quos ea perspiciatis, voluptate quaerat quia et debitis magni error iusto animi, optio similique earum eveniet, beatae sed? Autem voluptas, ullam numquam vero error optio. Ad molestiae hic sed provident eos quia quaerat deleniti, nihil obcaecati distinctio ducimus ipsa labore aspernatur quidem in exercitationem nobis corrupti iste eum, porro sequi voluptates. Commodi sed cum, maxime assumenda, quos eligendi dolorum, incidunt magnam velit amet quod vero? Eaque autem debitis vero eius aut sequi cumque perspiciatis omnis ipsa eos sapiente repellendus temporibus, veritatis quis hic repellat est accusantium asperiores et iste dolor. Veritatis, illum molestiae! Dicta accusantium repellendus natus, illum dolor, quae laboriosam, hic saepe assumenda incidunt cupiditate maiores. Laborum reiciendis mollitia repellat debitis exercitationem, fugit perspiciatis. Dolor itaque necessitatibus a doloribus voluptatum dolorem ab vitae eveniet quaerat molestias temporibus corrupti cupiditate veritatis ullam explicabo excepturi laboriosam delectus, illum vero, iste veniam fugit quam quidem. dolor sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
                'Lorem ipsum dolor sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
                'Lorem ipsum Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae, facere. Quas, architecto inventore nam, provident quia commodi odit doloribus ducimus et temporibus facere! Suscipit, asperiores nobis aperiam quod consequatur eos commodi explicabo error iusto sapiente modi dolor repellat consectetur aliquam obcaecati aspernatur. Laborum unde nulla consequatur, dignissimos quod quas, maxime eligendi ipsam omnis voluptate provident tempora. Ad quos ea perspiciatis, voluptate quaerat quia et debitis magni error iusto animi, optio similique earum eveniet, beatae sed? Autem voluptas, ullam numquam vero error optio. Ad molestiae hic sed provident eos quia quaerat deleniti, nihil obcaecati distinctio ducimus ipsa labore aspernatur quidem in exercitationem nobis corrupti iste eum, porro sequi voluptates. Commodi sed cum, maxime assumenda, quos eligendi dolorum, incidunt magnam velit amet quod vero? Eaque autem debitis vero eius aut sequi cumque perspiciatis omnis ipsa eos sapiente repellendus temporibus, veritatis quis hic repellat est accusantium asperiores et iste dolor. Veritatis, illum molestiae! Dicta accusantium repellendus natus, illum dolor, quae laboriosam, hic saepe assumenda incidunt cupiditate maiores. Laborum reiciendis mollitia repellat debitis exercitationem, fugit perspiciatis. Dolor itaque necessitatibus a doloribus voluptatum dolorem ab vitae eveniet quaerat molestias temporibus corrupti cupiditate veritatis ullam explicabo excepturi laboriosam delectus, illum vero, iste veniam fugit quam quidem.dolor sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
            ]
        },
    
]



]


