export const blogs = [

[
    {
        heading:'What is Data Science and how does it works',
        img: '/assets/images/blogs/ds.jpg',
        subHeading: 'Data Science Definition ',
        content: [
            'The field of Data Science is a topic of interest amongst organizations and skilled professionals that are looking on adding skills to their  repertoire and learn how to collect data and gain meaningful insights to aid the growth of business. Data is a true asset to any organization, but only when it is processed efficiently. The requirement of storage grew unprecedentedly when we stepped into the golden era of big data. Until a decade ago, the prime focus was on developing a state of the art infrastructure to store the aforementioned valuable data, to be used to process and arrive at business insights. This gave way to frameworks such as Hadoop that took care of the storage part. Gradually the focus shifted towards the processing of this data. And this shifted the limelight on data science. Let us take a look at what data science is, and how it is relevant in today’s current state of businesses and big data.',
            '𝐃𝐚𝐭𝐚 𝐒𝐜𝐢𝐞𝐧𝐜𝐞 𝐃𝐞𝐟𝐢𝐧𝐢𝐭𝐢𝐨𝐧',
            'Data Science is the analysis of data, where it is derived from, what it represents, and the numerous ways it can be used as valuable resources and inputs to create IT based solutions, strategies, and campaigns for businesses.',
            '𝐖𝐡𝐲 𝐝𝐨 𝐛𝐮𝐬𝐢𝐧𝐞𝐬𝐬𝐞𝐬 𝐝𝐞𝐩𝐞𝐧𝐝 𝐨𝐧 𝐃𝐚𝐭𝐚 𝐒𝐜𝐢𝐞𝐧𝐜𝐞?',
            'As we make major leaps in the field of technology, we have moved on from working with smaller sets of structured data to large pools of unstructured and semi-structured data derived from varied sources. The traditional Business Intelligence tools that were in use fall short in regards to the processing of this massive bank of unstructured data. Hence, we have to depend on Data Science which consists of more advanced tools to handle the large volumes of data derived from the different sources such as multimedia files, financial logs, instruments and sensors, marketing forms, and text files.',
            '𝐑𝐞𝐚𝐬𝐨𝐧𝐬 𝐰𝐡𝐲 𝐃𝐚𝐭𝐚 𝐒𝐜𝐢𝐞𝐧𝐜𝐞 𝐡𝐚𝐬 𝐛𝐞𝐜𝐨𝐦𝐞 𝐩𝐨𝐩𝐮𝐥𝐚𝐫 𝐚𝐦𝐨𝐧𝐠𝐬𝐭 𝐛𝐮𝐬𝐢𝐧𝐞𝐬𝐬𝐞𝐬:',
            '●Data Science is used in predictive analytics. It is used in weather forecasting by analysing the data that is collected from ships, aircraft, radars, and satellites, to develop models to forecast weather and predict natural calamities with impressive precision. This allows us to take the necessary measures at the right time to avoid maximum possible damage.',
            '●The product recommendations have never been this accurate with the conventional methods drawing insights using purchase and browser history coupled with basic demographic features. With the help of data science, vast volumes of diverse data can help models perform efficiently and effectively to offer precise recommendations.',
            '●Data science is extremely popular in effective decision making. Intelligent or self-driven cars are the perfect example. A smart vehicle collects data in real-time from the surroundings using a number of sensors such as cameras, lasers and radars to formulate a visual map. This vehicle then uses the data it collected to make crucial navigational decisions such as turning, speeding, stopping and so on.',
            '𝐖𝐡𝐨 𝐢𝐬 𝐚 𝐃𝐚𝐭𝐚 𝐒𝐜𝐢𝐞𝐧𝐭𝐢𝐬𝐭 𝐚𝐧𝐝 𝐖𝐡𝐚𝐭 𝐝𝐨 𝐭𝐡𝐞𝐲 𝐝𝐨?',
            'A data scientist is somebody that collects relevant data from numerous sources, stores and organizes the data, identifies questions of importance, decipher information that is useful, and process it. Finally, this information is used in business solutions, strategies and campaigns to enhance revenue generation.',
            '𝐖𝐡𝐲 𝐁𝐞𝐜𝐨𝐦𝐞 𝐚 𝐃𝐚𝐭𝐚 𝐒𝐜𝐢𝐞𝐧𝐭𝐢𝐬𝐭?',
            'According to reports, the demand for data scientists will increase by 28% by 2026. This proves the profession’s durability, demand, and longevity. It is also a well paying job. So, if you are looking for a secure career option, enroll for the online Data Science course at Book My Shiksha to gain skills in this rapidly growing field.'
            ]
    },
    {
        heading:'What is Machine Learing and how does it works',
        img: '/assets/images/blogs/code.svg',
        subHeading: '',
        content: [
            'Lorem ipsum dolorLorem ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae, facere. Quas, architecto inventore nam, provident quia commodi odit doloribus ducimus et temporibus facere! Suscipit, asperiores nobis aperiam quod consequatur eos commodi explicabo error iusto sapiente modi dolor repellat consectetur aliquam obcaecati aspernatur. Laborum unde nulla consequatur, dignissimos quod quas, maxime eligendi ipsam omnis voluptate provident tempora. Ad quos ea perspiciatis, voluptate quaerat quia et debitis magni error iusto animi, optio similique earum eveniet, beatae sed? Autem voluptas, ullam numquam vero error optio. Ad molestiae hic sed provident eos quia quaerat deleniti, nihil obcaecati distinctio ducimus ipsa labore aspernatur quidem in exercitationem nobis corrupti iste eum, porro sequi voluptates. Commodi sed cum, maxime assumenda, quos eligendi dolorum, incidunt magnam velit amet quod vero? Eaque autem debitis vero eius aut sequi cumque perspiciatis omnis ipsa eos sapiente repellendus temporibus, veritatis quis hic repellat est accusantium asperiores et iste dolor. Veritatis, illum molestiae! Dicta accusantium repellendus natus, illum dolor, quae laboriosam, hic saepe assumenda incidunt cupiditate maiores. Laborum reiciendis mollitia repellat debitis exercitationem, fugit perspiciatis. Dolor itaque necessitatibus a doloribus voluptatum dolorem ab vitae eveniet quaerat molestias temporibus corrupti cupiditate veritatis ullam explicabo excepturi laboriosam delectus, illum vero, iste veniam fugit quam quidem. sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
            'Lorem ipsum dolorLorem ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae, facere. Quas, architecto inventore nam, provident quia commodi odit doloribus ducimus et temporibus facere! Suscipit, asperiores nobis aperiam quod consequatur eos commodi explicabo error iusto sapiente modi dolor repellat consectetur aliquam obcaecati aspernatur. Laborum unde nulla consequatur, dignissimos quod quas, maxime eligendi ipsam omnis voluptate provident tempora. Ad quos ea perspiciatis, voluptate quaerat quia et debitis magni error iusto animi, optio similique earum eveniet, beatae sed? Autem voluptas, ullam numquam vero error optio. Ad molestiae hic sed provident eos quia quaerat deleniti, nihil obcaecati distinctio ducimus ipsa labore aspernatur quidem in exercitationem nobis corrupti iste eum, porro sequi voluptates. Commodi sed cum, maxime assumenda, quos eligendi dolorum, incidunt magnam velit amet quod vero? Eaque autem debitis vero eius aut sequi cumque perspiciatis omnis ipsa eos sapiente repellendus temporibus, veritatis quis hic repellat est accusantium asperiores et iste dolor. Veritatis, illum molestiae! Dicta accusantium repellendus natus, illum dolor, quae laboriosam, hic saepe assumenda incidunt cupiditate maiores. Laborum reiciendis mollitia repellat debitis exercitationem, fugit perspiciatis. Dolor itaque necessitatibus a doloribus voluptatum dolorem ab vitae eveniet quaerat molestias temporibus corrupti cupiditate veritatis ullam explicabo excepturi laboriosam delectus, illum vero, iste veniam fugit quam quidem. sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
        ]
    },
    {
        heading:'What is RPA and how does it works',
        img: '/assets/images/blogs/rpa.svg',
        subHeading: '',
        content: [
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
            'Lorem ipsum dolorLorem ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae, facere. Quas, architecto inventore nam, provident quia commodi odit doloribus ducimus et temporibus facere! Suscipit, asperiores nobis aperiam quod consequatur eos commodi explicabo error iusto sapiente modi dolor repellat consectetur aliquam obcaecati aspernatur. Laborum unde nulla consequatur, dignissimos quod quas, maxime eligendi ipsam omnis voluptate provident tempora. Ad quos ea perspiciatis, voluptate quaerat quia et debitis magni error iusto animi, optio similique earum eveniet, beatae sed? Autem voluptas, ullam numquam vero error optio. Ad molestiae hic sed provident eos quia quaerat deleniti, nihil obcaecati distinctio ducimus ipsa labore aspernatur quidem in exercitationem nobis corrupti iste eum, porro sequi voluptates. Commodi sed cum, maxime assumenda, quos eligendi dolorum, incidunt magnam velit amet quod vero? Eaque autem debitis vero eius aut sequi cumque perspiciatis omnis ipsa eos sapiente repellendus temporibus, veritatis quis hic repellat est accusantium asperiores et iste dolor. Veritatis, illum molestiae! Dicta accusantium repellendus natus, illum dolor, quae laboriosam, hic saepe assumenda incidunt cupiditate maiores. Laborum reiciendis mollitia repellat debitis exercitationem, fugit perspiciatis. Dolor itaque necessitatibus a doloribus voluptatum dolorem ab vitae eveniet quaerat molestias temporibus corrupti cupiditate veritatis ullam explicabo excepturi laboriosam delectus, illum vero, iste veniam fugit quam quidem. sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
            'Lorem ipsum dolorLorem ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae, facere. Quas, architecto inventore nam, provident quia commodi odit doloribus ducimus et temporibus facere! Suscipit, asperiores nobis aperiam quod consequatur eos commodi explicabo error iusto sapiente modi dolor repellat consectetur aliquam obcaecati aspernatur. Laborum unde nulla consequatur, dignissimos quod quas, maxime eligendi ipsam omnis voluptate provident tempora. Ad quos ea perspiciatis, voluptate quaerat quia et debitis magni error iusto animi, optio similique earum eveniet, beatae sed? Autem voluptas, ullam numquam vero error optio. Ad molestiae hic sed provident eos quia quaerat deleniti, nihil obcaecati distinctio ducimus ipsa labore aspernatur quidem in exercitationem nobis corrupti iste eum, porro sequi voluptates. Commodi sed cum, maxime assumenda, quos eligendi dolorum, incidunt magnam velit amet quod vero? Eaque autem debitis vero eius aut sequi cumque perspiciatis omnis ipsa eos sapiente repellendus temporibus, veritatis quis hic repellat est accusantium asperiores et iste dolor. Veritatis, illum molestiae! Dicta accusantium repellendus natus, illum dolor, quae laboriosam, hic saepe assumenda incidunt cupiditate maiores. Laborum reiciendis mollitia repellat debitis exercitationem, fugit perspiciatis. Dolor itaque necessitatibus a doloribus voluptatum dolorem ab vitae eveniet quaerat molestias temporibus corrupti cupiditate veritatis ullam explicabo excepturi laboriosam delectus, illum vero, iste veniam fugit quam quidem. sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
        ]
    },
],

[
    
        {
            heading:'What is Social Meadia Marketing',
            img: '/assets/images/blogs/dm.png',
            subHeading: '',
            content: [
                'Lorem ipsumLorem ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae, facere. Quas, architecto inventore nam, provident quia commodi odit doloribus ducimus et temporibus facere! Suscipit, asperiores nobis aperiam quod consequatur eos commodi explicabo error iusto sapiente modi dolor repellat consectetur aliquam obcaecati aspernatur. Laborum unde nulla consequatur, dignissimos quod quas, maxime eligendi ipsam omnis voluptate provident tempora. Ad quos ea perspiciatis, voluptate quaerat quia et debitis magni error iusto animi, optio similique earum eveniet, beatae sed? Autem voluptas, ullam numquam vero error optio. Ad molestiae hic sed provident eos quia quaerat deleniti, nihil obcaecati distinctio ducimus ipsa labore aspernatur quidem in exercitationem nobis corrupti iste eum, porro sequi voluptates. Commodi sed cum, maxime assumenda, quos eligendi dolorum, incidunt magnam velit amet quod vero? Eaque autem debitis vero eius aut sequi cumque perspiciatis omnis ipsa eos sapiente repellendus temporibus, veritatis quis hic repellat est accusantium asperiores et iste dolor. Veritatis, illum molestiae! Dicta accusantium repellendus natus, illum dolor, quae laboriosam, hic saepe assumenda incidunt cupiditate maiores. Laborum reiciendis mollitia repellat debitis exercitationem, fugit perspiciatis. Dolor itaque necessitatibus a doloribus voluptatum dolorem ab vitae eveniet quaerat molestias temporibus corrupti cupiditate veritatis ullam explicabo excepturi laboriosam delectus, illum vero, iste veniam fugit quam quidem. dolor sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
                'Lorem ipsum dolor sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
                'Lorem ipsumLorem ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae, facere. Quas, architecto inventore nam, provident quia commodi odit doloribus ducimus et temporibus facere! Suscipit, asperiores nobis aperiam quod consequatur eos commodi explicabo error iusto sapiente modi dolor repellat consectetur aliquam obcaecati aspernatur. Laborum unde nulla consequatur, dignissimos quod quas, maxime eligendi ipsam omnis voluptate provident tempora. Ad quos ea perspiciatis, voluptate quaerat quia et debitis magni error iusto animi, optio similique earum eveniet, beatae sed? Autem voluptas, ullam numquam vero error optio. Ad molestiae hic sed provident eos quia quaerat deleniti, nihil obcaecati distinctio ducimus ipsa labore aspernatur quidem in exercitationem nobis corrupti iste eum, porro sequi voluptates. Commodi sed cum, maxime assumenda, quos eligendi dolorum, incidunt magnam velit amet quod vero? Eaque autem debitis vero eius aut sequi cumque perspiciatis omnis ipsa eos sapiente repellendus temporibus, veritatis quis hic repellat est accusantium asperiores et iste dolor. Veritatis, illum molestiae! Dicta accusantium repellendus natus, illum dolor, quae laboriosam, hic saepe assumenda incidunt cupiditate maiores. Laborum reiciendis mollitia repellat debitis exercitationem, fugit perspiciatis. Dolor itaque necessitatibus a doloribus voluptatum dolorem ab vitae eveniet quaerat molestias temporibus corrupti cupiditate veritatis ullam explicabo excepturi laboriosam delectus, illum vero, iste veniam fugit quam quidem. dolor sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
                'Lorem ipsum dolor sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
            ]
        },
        {
            heading:'How can you grow your business with digital marketing',
            img: '/assets/images/blogs/creative.jpg',
            subHeading: '',
            content: [
                'Lorem ipsum dolor sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
                'Lorem ipsumLorem ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae, facere. Quas, architecto inventore nam, provident quia commodi odit doloribus ducimus et temporibus facere! Suscipit, asperiores nobis aperiam quod consequatur eos commodi explicabo error iusto sapiente modi dolor repellat consectetur aliquam obcaecati aspernatur. Laborum unde nulla consequatur, dignissimos quod quas, maxime eligendi ipsam omnis voluptate provident tempora. Ad quos ea perspiciatis, voluptate quaerat quia et debitis magni error iusto animi, optio similique earum eveniet, beatae sed? Autem voluptas, ullam numquam vero error optio. Ad molestiae hic sed provident eos quia quaerat deleniti, nihil obcaecati distinctio ducimus ipsa labore aspernatur quidem in exercitationem nobis corrupti iste eum, porro sequi voluptates. Commodi sed cum, maxime assumenda, quos eligendi dolorum, incidunt magnam velit amet quod vero? Eaque autem debitis vero eius aut sequi cumque perspiciatis omnis ipsa eos sapiente repellendus temporibus, veritatis quis hic repellat est accusantium asperiores et iste dolor. Veritatis, illum molestiae! Dicta accusantium repellendus natus, illum dolor, quae laboriosam, hic saepe assumenda incidunt cupiditate maiores. Laborum reiciendis mollitia repellat debitis exercitationem, fugit perspiciatis. Dolor itaque necessitatibus a doloribus voluptatum dolorem ab vitae eveniet quaerat molestias temporibus corrupti cupiditate veritatis ullam explicabo excepturi laboriosam delectus, illum vero, iste veniam fugit quam quidem. dolor sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
                'Lorem ipsum dolor sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
                'Lorem ipsum Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae, facere. Quas, architecto inventore nam, provident quia commodi odit doloribus ducimus et temporibus facere! Suscipit, asperiores nobis aperiam quod consequatur eos commodi explicabo error iusto sapiente modi dolor repellat consectetur aliquam obcaecati aspernatur. Laborum unde nulla consequatur, dignissimos quod quas, maxime eligendi ipsam omnis voluptate provident tempora. Ad quos ea perspiciatis, voluptate quaerat quia et debitis magni error iusto animi, optio similique earum eveniet, beatae sed? Autem voluptas, ullam numquam vero error optio. Ad molestiae hic sed provident eos quia quaerat deleniti, nihil obcaecati distinctio ducimus ipsa labore aspernatur quidem in exercitationem nobis corrupti iste eum, porro sequi voluptates. Commodi sed cum, maxime assumenda, quos eligendi dolorum, incidunt magnam velit amet quod vero? Eaque autem debitis vero eius aut sequi cumque perspiciatis omnis ipsa eos sapiente repellendus temporibus, veritatis quis hic repellat est accusantium asperiores et iste dolor. Veritatis, illum molestiae! Dicta accusantium repellendus natus, illum dolor, quae laboriosam, hic saepe assumenda incidunt cupiditate maiores. Laborum reiciendis mollitia repellat debitis exercitationem, fugit perspiciatis. Dolor itaque necessitatibus a doloribus voluptatum dolorem ab vitae eveniet quaerat molestias temporibus corrupti cupiditate veritatis ullam explicabo excepturi laboriosam delectus, illum vero, iste veniam fugit quam quidem.dolor sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
            ]
        },
        {
            heading:'What is SEO and how does it works',
            img: '/assets/images/blogs/seo.jpg',
            subHeading: '',
            content: [
                'Lorem ipsum Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae, facere. Quas, architecto inventore nam, provident quia commodi odit doloribus ducimus et temporibus facere! Suscipit, asperiores nobis aperiam quod consequatur eos commodi explicabo error iusto sapiente modi dolor repellat consectetur aliquam obcaecati aspernatur. Laborum unde nulla consequatur, dignissimos quod quas, maxime eligendi ipsam omnis voluptate provident tempora. Ad quos ea perspiciatis, voluptate quaerat quia et debitis magni error iusto animi, optio similique earum eveniet, beatae sed? Autem voluptas, ullam numquam vero error optio. Ad molestiae hic sed provident eos quia quaerat deleniti, nihil obcaecati distinctio ducimus ipsa labore aspernatur quidem in exercitationem nobis corrupti iste eum, porro sequi voluptates. Commodi sed cum, maxime assumenda, quos eligendi dolorum, incidunt magnam velit amet quod vero? Eaque autem debitis vero eius aut sequi cumque perspiciatis omnis ipsa eos sapiente repellendus temporibus, veritatis quis hic repellat est accusantium asperiores et iste dolor. Veritatis, illum molestiae! Dicta accusantium repellendus natus, illum dolor, quae laboriosam, hic saepe assumenda incidunt cupiditate maiores. Laborum reiciendis mollitia repellat debitis exercitationem, fugit perspiciatis. Dolor itaque necessitatibus a doloribus voluptatum dolorem ab vitae eveniet quaerat molestias temporibus corrupti cupiditate veritatis ullam explicabo excepturi laboriosam delectus, illum vero, iste veniam fugit quam quidem.dolor sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
                'Lorem ipsum dolor sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
                'Lorem ipsumLorem ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae, facere. Quas, architecto inventore nam, provident quia commodi odit doloribus ducimus et temporibus facere! Suscipit, asperiores nobis aperiam quod consequatur eos commodi explicabo error iusto sapiente modi dolor repellat consectetur aliquam obcaecati aspernatur. Laborum unde nulla consequatur, dignissimos quod quas, maxime eligendi ipsam omnis voluptate provident tempora. Ad quos ea perspiciatis, voluptate quaerat quia et debitis magni error iusto animi, optio similique earum eveniet, beatae sed? Autem voluptas, ullam numquam vero error optio. Ad molestiae hic sed provident eos quia quaerat deleniti, nihil obcaecati distinctio ducimus ipsa labore aspernatur quidem in exercitationem nobis corrupti iste eum, porro sequi voluptates. Commodi sed cum, maxime assumenda, quos eligendi dolorum, incidunt magnam velit amet quod vero? Eaque autem debitis vero eius aut sequi cumque perspiciatis omnis ipsa eos sapiente repellendus temporibus, veritatis quis hic repellat est accusantium asperiores et iste dolor. Veritatis, illum molestiae! Dicta accusantium repellendus natus, illum dolor, quae laboriosam, hic saepe assumenda incidunt cupiditate maiores. Laborum reiciendis mollitia repellat debitis exercitationem, fugit perspiciatis. Dolor itaque necessitatibus a doloribus voluptatum dolorem ab vitae eveniet quaerat molestias temporibus corrupti cupiditate veritatis ullam explicabo excepturi laboriosam delectus, illum vero, iste veniam fugit quam quidem. dolor sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
                'Lorem ipsum dolor sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
            ]
        },
    
],

[
    
        {
            heading:'Most demanding jobs in IT-Sector by 2022',
            img: '/assets/images/blogs/openSourse.svg',
            subHeading: '',
            content: [
                'Lorem ipsum dolor sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
                'Lorem ipsumLorem ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae, facere. Quas, architecto inventore nam, provident quia commodi odit doloribus ducimus et temporibus facere! Suscipit, asperiores nobis aperiam quod consequatur eos commodi explicabo error iusto sapiente modi dolor repellat consectetur aliquam obcaecati aspernatur. Laborum unde nulla consequatur, dignissimos quod quas, maxime eligendi ipsam omnis voluptate provident tempora. Ad quos ea perspiciatis, voluptate quaerat quia et debitis magni error iusto animi, optio similique earum eveniet, beatae sed? Autem voluptas, ullam numquam vero error optio. Ad molestiae hic sed provident eos quia quaerat deleniti, nihil obcaecati distinctio ducimus ipsa labore aspernatur quidem in exercitationem nobis corrupti iste eum, porro sequi voluptates. Commodi sed cum, maxime assumenda, quos eligendi dolorum, incidunt magnam velit amet quod vero? Eaque autem debitis vero eius aut sequi cumque perspiciatis omnis ipsa eos sapiente repellendus temporibus, veritatis quis hic repellat est accusantium asperiores et iste dolor. Veritatis, illum molestiae! Dicta accusantium repellendus natus, illum dolor, quae laboriosam, hic saepe assumenda incidunt cupiditate maiores. Laborum reiciendis mollitia repellat debitis exercitationem, fugit perspiciatis. Dolor itaque necessitatibus a doloribus voluptatum dolorem ab vitae eveniet quaerat molestias temporibus corrupti cupiditate veritatis ullam explicabo excepturi laboriosam delectus, illum vero, iste veniam fugit quam quidem. dolor sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
                'Lorem ipsum dolor sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
                'Lorem ipsumLorem ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae, facere. Quas, architecto inventore nam, provident quia commodi odit doloribus ducimus et temporibus facere! Suscipit, asperiores nobis aperiam quod consequatur eos commodi explicabo error iusto sapiente modi dolor repellat consectetur aliquam obcaecati aspernatur. Laborum unde nulla consequatur, dignissimos quod quas, maxime eligendi ipsam omnis voluptate provident tempora. Ad quos ea perspiciatis, voluptate quaerat quia et debitis magni error iusto animi, optio similique earum eveniet, beatae sed? Autem voluptas, ullam numquam vero error optio. Ad molestiae hic sed provident eos quia quaerat deleniti, nihil obcaecati distinctio ducimus ipsa labore aspernatur quidem in exercitationem nobis corrupti iste eum, porro sequi voluptates. Commodi sed cum, maxime assumenda, quos eligendi dolorum, incidunt magnam velit amet quod vero? Eaque autem debitis vero eius aut sequi cumque perspiciatis omnis ipsa eos sapiente repellendus temporibus, veritatis quis hic repellat est accusantium asperiores et iste dolor. Veritatis, illum molestiae! Dicta accusantium repellendus natus, illum dolor, quae laboriosam, hic saepe assumenda incidunt cupiditate maiores. Laborum reiciendis mollitia repellat debitis exercitationem, fugit perspiciatis. Dolor itaque necessitatibus a doloribus voluptatum dolorem ab vitae eveniet quaerat molestias temporibus corrupti cupiditate veritatis ullam explicabo excepturi laboriosam delectus, illum vero, iste veniam fugit quam quidem. dolor sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
            ]
        },
        {
            heading:'How to get a fresher job as a web developer',
            img: '/assets/images/blogs/code.svg',
            subHeading: '',
            content: [
                'Lorem ipsum Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae, facere. Quas, architecto inventore nam, provident quia commodi odit doloribus ducimus et temporibus facere! Suscipit, asperiores nobis aperiam quod consequatur eos commodi explicabo error iusto sapiente modi dolor repellat consectetur aliquam obcaecati aspernatur. Laborum unde nulla consequatur, dignissimos quod quas, maxime eligendi ipsam omnis voluptate provident tempora. Ad quos ea perspiciatis, voluptate quaerat quia et debitis magni error iusto animi, optio similique earum eveniet, beatae sed? Autem voluptas, ullam numquam vero error optio. Ad molestiae hic sed provident eos quia quaerat deleniti, nihil obcaecati distinctio ducimus ipsa labore aspernatur quidem in exercitationem nobis corrupti iste eum, porro sequi voluptates. Commodi sed cum, maxime assumenda, quos eligendi dolorum, incidunt magnam velit amet quod vero? Eaque autem debitis vero eius aut sequi cumque perspiciatis omnis ipsa eos sapiente repellendus temporibus, veritatis quis hic repellat est accusantium asperiores et iste dolor. Veritatis, illum molestiae! Dicta accusantium repellendus natus, illum dolor, quae laboriosam, hic saepe assumenda incidunt cupiditate maiores. Laborum reiciendis mollitia repellat debitis exercitationem, fugit perspiciatis. Dolor itaque necessitatibus a doloribus voluptatum dolorem ab vitae eveniet quaerat molestias temporibus corrupti cupiditate veritatis ullam explicabo excepturi laboriosam delectus, illum vero, iste veniam fugit quam quidem.dolor sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
                'Lorem ipsum dolor sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
                'Lorem ipsum Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae, facere. Quas, architecto inventore nam, provident quia commodi odit doloribus ducimus et temporibus facere! Suscipit, asperiores nobis aperiam quod consequatur eos commodi explicabo error iusto sapiente modi dolor repellat consectetur aliquam obcaecati aspernatur. Laborum unde nulla consequatur, dignissimos quod quas, maxime eligendi ipsam omnis voluptate provident tempora. Ad quos ea perspiciatis, voluptate quaerat quia et debitis magni error iusto animi, optio similique earum eveniet, beatae sed? Autem voluptas, ullam numquam vero error optio. Ad molestiae hic sed provident eos quia quaerat deleniti, nihil obcaecati distinctio ducimus ipsa labore aspernatur quidem in exercitationem nobis corrupti iste eum, porro sequi voluptates. Commodi sed cum, maxime assumenda, quos eligendi dolorum, incidunt magnam velit amet quod vero? Eaque autem debitis vero eius aut sequi cumque perspiciatis omnis ipsa eos sapiente repellendus temporibus, veritatis quis hic repellat est accusantium asperiores et iste dolor. Veritatis, illum molestiae! Dicta accusantium repellendus natus, illum dolor, quae laboriosam, hic saepe assumenda incidunt cupiditate maiores. Laborum reiciendis mollitia repellat debitis exercitationem, fugit perspiciatis. Dolor itaque necessitatibus a doloribus voluptatum dolorem ab vitae eveniet quaerat molestias temporibus corrupti cupiditate veritatis ullam explicabo excepturi laboriosam delectus, illum vero, iste veniam fugit quam quidem.dolor sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
                'Lorem ipsum dolor sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
            ]
        },
        {
            heading:'How to land your internship in Data Science ',
            img: '/assets/images/blogs/edu.svg',
            subHeading: '',
            content: [
                'Lorem ipsum dolor sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
                'Lorem ipsumLorem ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae, facere. Quas, architecto inventore nam, provident quia commodi odit doloribus ducimus et temporibus facere! Suscipit, asperiores nobis aperiam quod consequatur eos commodi explicabo error iusto sapiente modi dolor repellat consectetur aliquam obcaecati aspernatur. Laborum unde nulla consequatur, dignissimos quod quas, maxime eligendi ipsam omnis voluptate provident tempora. Ad quos ea perspiciatis, voluptate quaerat quia et debitis magni error iusto animi, optio similique earum eveniet, beatae sed? Autem voluptas, ullam numquam vero error optio. Ad molestiae hic sed provident eos quia quaerat deleniti, nihil obcaecati distinctio ducimus ipsa labore aspernatur quidem in exercitationem nobis corrupti iste eum, porro sequi voluptates. Commodi sed cum, maxime assumenda, quos eligendi dolorum, incidunt magnam velit amet quod vero? Eaque autem debitis vero eius aut sequi cumque perspiciatis omnis ipsa eos sapiente repellendus temporibus, veritatis quis hic repellat est accusantium asperiores et iste dolor. Veritatis, illum molestiae! Dicta accusantium repellendus natus, illum dolor, quae laboriosam, hic saepe assumenda incidunt cupiditate maiores. Laborum reiciendis mollitia repellat debitis exercitationem, fugit perspiciatis. Dolor itaque necessitatibus a doloribus voluptatum dolorem ab vitae eveniet quaerat molestias temporibus corrupti cupiditate veritatis ullam explicabo excepturi laboriosam delectus, illum vero, iste veniam fugit quam quidem. dolor sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
                'Lorem ipsum dolor sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
                'Lorem ipsum Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae, facere. Quas, architecto inventore nam, provident quia commodi odit doloribus ducimus et temporibus facere! Suscipit, asperiores nobis aperiam quod consequatur eos commodi explicabo error iusto sapiente modi dolor repellat consectetur aliquam obcaecati aspernatur. Laborum unde nulla consequatur, dignissimos quod quas, maxime eligendi ipsam omnis voluptate provident tempora. Ad quos ea perspiciatis, voluptate quaerat quia et debitis magni error iusto animi, optio similique earum eveniet, beatae sed? Autem voluptas, ullam numquam vero error optio. Ad molestiae hic sed provident eos quia quaerat deleniti, nihil obcaecati distinctio ducimus ipsa labore aspernatur quidem in exercitationem nobis corrupti iste eum, porro sequi voluptates. Commodi sed cum, maxime assumenda, quos eligendi dolorum, incidunt magnam velit amet quod vero? Eaque autem debitis vero eius aut sequi cumque perspiciatis omnis ipsa eos sapiente repellendus temporibus, veritatis quis hic repellat est accusantium asperiores et iste dolor. Veritatis, illum molestiae! Dicta accusantium repellendus natus, illum dolor, quae laboriosam, hic saepe assumenda incidunt cupiditate maiores. Laborum reiciendis mollitia repellat debitis exercitationem, fugit perspiciatis. Dolor itaque necessitatibus a doloribus voluptatum dolorem ab vitae eveniet quaerat molestias temporibus corrupti cupiditate veritatis ullam explicabo excepturi laboriosam delectus, illum vero, iste veniam fugit quam quidem.dolor sit amet consectetur adipisicing elit. A, saepe? Nostrum tempora, id inventore officiis veniam rerum, suscipit sunt nemo quidem natus cupiditate facere! Earum libero impedit pariatur nobis odit?',
            ]
        },
    
]



]


