export const courses = [
    {
        id:1,
        courseName:'Basics of Python with Data Structures and Algorithms',
        aboutCourse:'Lorem ipsum dolor sit amet consectetur, adipisicia vel libero quod sequi, ea ipsam? Hic, architecto dolores quo et vitae optio sit sint.',
        about: [
            "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi amet non asperiores aspernatur ab cumque dolores reprehenderit adipisci error porro magni praesentium a quas excepturi enim veritatis impedit rerum vitae, similique ratione possimus numquam, deleniti voluptatibus! Nulla cumque omnis eum odio commodi doloribus facilis, rem nobis aperiam quidem consequatur architecto doloremque. Magnam mollitia voluptatibus excepturi incidunt autem ut accusamus aliquid quod qui omnis aperiam perspiciatis provident, quam sit, culpa dignissimos unde, accusantium deserunt quos nam pariatur? Earum asperiores doloremque et debitis magni itaque sint quidem dolore? Atque aliquam neque tempore recusandae sunt voluptatum in, maiores dolore incidunt dolorem? Tenetur, praesentium?",
            "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi amet non asperiores aspernatur ab cumque dolores reprehenderit adipisci error porro magni praesentium a quas excepturi enim veritatis impedit rerum vitae, similique ratione possimus numquam, deleniti voluptatibus! Nulla cumque omnis eum odio commodi doloribus facilis, rem nobis aperiam quidem consequatur architecto doloremque. Magnam mollitia voluptatibus excepturi incidunt autem ut accusamus aliquid quod qui omnis aperiam perspiciatis provident, quam sit, culpa dignissimos unde, accusantium deserunt quos nam pariatur? Earum asperiores doloremque et debitis magni itaque sint quidem dolore? Atque aliquam neque tempore recusandae sunt voluptatum in, maiores dolore incidunt dolorem? Tenetur, praesentium?",
            "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi amet non asperiores aspernatur ab cumque dolores reprehenderit adipisci error porro magni praesentium a quas excepturi enim veritatis impedit rerum vitae, similique ratione possimus numquam, deleniti voluptatibus! Nulla cumque omnis eum odio commodi doloribus facilis, rem nobis aperiam quidem consequatur architecto doloremque. Magnam mollitia voluptatibus excepturi incidunt autem ut accusamus aliquid quod qui omnis aperiam perspiciatis provident, quam sit, culpa dignissimos unde, accusantium deserunt quos nam pariatur? Earum asperiores doloremque et debitis magni itaque sint quidem dolore? Atque aliquam neque tempore recusandae sunt voluptatum in, maiores dolore incidunt dolorem? Tenetur, praesentium?",
            "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi amet non asperiores aspernatur ab cumque dolores reprehenderit adipisci error porro magni praesentium a quas excepturi enim veritatis impedit rerum vitae, similique ratione possimus numquam, deleniti voluptatibus! Nulla cumque omnis eum odio commodi doloribus facilis, rem nobis aperiam quidem consequatur architecto doloremque. Magnam mollitia voluptatibus excepturi incidunt autem ut accusamus aliquid quod qui omnis aperiam perspiciatis provident, quam sit, culpa dignissimos unde, accusantium deserunt quos nam pariatur? Earum asperiores doloremque et debitis magni itaque sint quidem dolore? Atque aliquam neque tempore recusandae sunt voluptatum in, maiores dolore incidunt dolorem? Tenetur, praesentium?",
        ] 
            
        
    }
]