export const Titles:any = {
      Python_Training_course_DelhiNCR:'Python Course in Delhi | Python Training in Delhi',
      Data_Science_Training_course_DelhiNCR:'Data Science Course in Delhi | Data Science Training in Delhi',
      Machine_Learning_Training_course_DelhiNCR:2,
      Deep_Learning_Training_course_DelhiNCR:3,
      Artificial_Inteligence_Training_course_DelhiNCR:4,
      Diploma_in_DataScience_course_DelhiNCR:5,
      Diploma_in_Machine_Learning_course_DelhiNCR:6,
      Masters_in_DataScience_course_DelhiNCR:7,
      Masters_in_Machine_Learning_course_DelhiNCR:8,
      SEO_course_DelhiNCR:9,
      RPA_course_DelhiNCR:10,
      Java_course_DelhiNCR:11,
      NET_course_DelhiNCR:12,
      VBA_course_DelhiNCR:13,
      PHP_course_DelhiNCR:14,
      HTML5_CSS3_JS_course_DelhiNCR:15,
      Angular_course_DelhiNCR:16,
      NodeJs_course_DelhiNCR:17,
      React_course_DelhiNCR:18,
      Pyhton_Django_course_DelhiNCR:19,
      MongoDB_course_DelhiNCR:20,
      SQL_course_DelhiNCR:21,
      Oracle_course_DelhiNCR:22,
      PowerBi_course_DelhiNCR:23,
      Tableau_course_DelhiNCR:24,
      Social_media_Optimization_course_DelhiNCR:25,
      Pay_per_click_course_DelhiNCR:26,
      Google_ads_certification_course_DelhiNCR:27,
      Facebook_ads_certification_course_DelhiNCR:28,
      Social_media_promotion_course_DelhiNCR:29,
      Email_marketing_course_DelhiNCR:30,
}